<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="309" started-at="2017-01-22T07:19:42Z" finished-at="2017-01-22T07:19:43Z">
    <groups>
      <group name="smoke">
        <method signature="Test_Scenario.test_Scenario(java.util.Map)[pri:0, instance:ScenarioComponent.Test_Scenario@64729b1e]" name="test_Scenario" class="ScenarioComponent.Test_Scenario"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Default test" duration-ms="309" started-at="2017-01-22T07:19:42Z" finished-at="2017-01-22T07:19:43Z">
      <class name="ScenarioComponent.Test_Scenario">
        <test-method status="FAIL" signature="test_Scenario(java.util.Map)[pri:0, instance:ScenarioComponent.Test_Scenario@64729b1e]" name="test_Scenario" duration-ms="0" started-at="2017-01-22T12:49:43Z" data-provider="dp_validsearch" finished-at="2017-01-22T12:49:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:143)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:426)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.NullPointerException
	at GenericComponent.ExcelReadeWrite.getRowCount(ExcelReadeWrite.java:30)
	at DataProviderComponent.DP_Search.getXlData(DP_Search.java:39)
	at DataProviderComponent.DP_Search.getValidXlData(DP_Search.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)
	... 20 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Scenario -->
      </class> <!-- ScenarioComponent.Test_Scenario -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
